### ISSUE TITLE
Access denied when redirecting to http://meet.jitsi:3000/api/config

### ISSUE THREAD

**Issue by mjtnajafi** [D3473R/jitsi-keycloak#14]
Hello, when I login using keycloak user I get the error, you can see in the below picture

![image](https://user-images.githubusercontent.com/16173586/89618188-e36a8f80-d8a0-11ea-81cc-3f79a4498c64.png)

**Comment by D3473R** [comment]
HI, have you whitelisted the domain in the keycloak web origins?

**Comment by mjtnajafi** [comment]
This is my jitsi client configuration in keycloak and the web origins is set to *
![image](https://user-images.githubusercontent.com/16173586/90108010-ed880480-dd5e-11ea-80ce-7c4d585d5e8c.png)

**Comment by D3473R** [comment]
Are you using a wrong client_id? In the request the id is `myjitsi` and in your keycloak config its `jitsi`?
