### ISSUE TITLE
Feature proposal: set Room via URL parameter

### ISSUE THREAD

**Issue by teutat3s** [D3473R/jitsi-keycloak#16]
Hello @D3473R,
thank you for making Keycloak work with Jitsi JWT auth!

I would like to use the undocumented `tokenAuthUrl` in Jitsi's `config.js` to redirect guests to auth.meet.mydomain.com when they click "I am the host". It would be great if I could pass the already entered room name to `jitsi-keycloak` via a URL parameter, like [this](https://community.jitsi.org/t/several-token-auth-issues/77237):
```
// Custom page on my site that authenticates users, builds a jwt and redirects back to {REFERER_URL}?jwt=x.y.z
tokenAuthUrl: 'https://myserver.mydomain.us/api/jitsi_token?room={room}',
``` 

Maybe something like this would be a proper way to implement this?
https://stackoverflow.com/questions/46878528/vuejs-bind-input-to-url-param/60786867#60786867

Looking forward to your feedback / thoughts. If you agree that this would be a nice feature, I'd be willing to create a PR, too.

**Comment by D3473R** [comment]
Awesome! I didn't know that such a config parameter existed already. 
Surely I can parse a url parameter to redirect to the correct jitsi room.
I will take a look at it later today :)

**Comment by teutat3s** [comment]
Great news, thanks for the swift response!

**Comment by D3473R** [comment]
Reading the room from the url was added in https://github.com/D3473R/jitsi-keycloak/commit/2d084fb50cd5313211ccf75ccf5e9e1c5e3444f6
I've used a url param, not a query to be consistent with the jitsi room url eg. https://meet.example.com/roomname
So the tokenAuthUrl should look like this: `tokenAuthUrl: 'https://auth.meet.example.com/{room}',`
Sadly I couldn't get the tokenAuthUrl to work with my docker-jitsi-meet setup, so I have tested it only manually right now (Opening https://auth.meet.example.com/roomname)

**Comment by teutat3s** [comment]
Nice - I will test this now, too.

For me the following worked to setup `tokenAuthUrl` in our docker-jitsi-meet setup:
Go to your configs directory and find the following lines in `web/config.js`:
```
...
    // If true all users without a token will be considered guests and all users
    // with token will be considered non-guests. Only guests will be allowed to
    // edit their profile.
    enableUserRolesBasedOnToken: false,

    // Whether or not some features are checked based on token.
    // enableFeaturesBasedOnToken: false,
...
```

Below that, I just added:
```
tokenAuthUrl: 'https://auth.meet.mydomain.com',
```
and did
```
docker restart docker-jitsi-meet_web_1
```

I hope you can get it to work with your setup, too.

**Comment by teutat3s** [comment]
I can confirm that https://auth.meet.example.com/roomname works by creating a pop-up request in the current tab.

Sadly when clicking "I am the host" in a Jitsi room without a moderator, the room name is not inserted into the `Room` input field of https://auth.meet.example.com and stays set to the default `meeting`.

Can I help you with debugging in some way?

**Comment by teutat3s** [comment]
Sorry for the fuzz - I got it working now.

My instructions above should work for [docker-jitsi-meet versions prior to `stable-5076`](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-5076), but starting with that version, it builds the `config.js` for the `web` container on each boot. So to make adjustments you could do the following:
```
docker exec -it docker-jitsi-meet_web_1 bash
```
```
apt update && apt install -y vim
vim /defaults/config.js
```
Make the above mentioned adjustment in that file, and the changes will stick. So now 
```
tokenAuthUrl: 'https://auth.meet.example.com/{room}',
```
works for me. :tada: 

Thanks for integrating it so quickly!

**Comment by teutat3s** [comment]
One more question on the last changes: 
When I click "Open Jitsi" in https://auth.meet.example.com now there's a Yellow Pop-Up Banner warning from Firefox, that wasn't there before. What might be causing this?

**Comment by D3473R** [comment]
Ah, yeah I am running the latest docker image, therefore my config was getting overwritten.
Thanks for the hint! We could open a issue on the docker-jitsi-meet project and ask for additional config support via the .env file.
The pop-up banner is caused by trying to open jitsi in a new tab automatically if the app gets called with a room name set.
I changed it to open jitsi in the same tab which is better anyway, because we don't need the jitsi-keycloak app anymore if have logged in successfully.

**Comment by teutat3s** [comment]
Nice job! I think this issue can be closed then - you've got one very happy user here.
