### ISSUE TITLE
Malformed URL after signing in

### ISSUE THREAD

**Issue by brendan-mccoy** [d3473r/jitsi-keycloak#26]
I'm sure I'm doing something wrong, but I get to where I can log in with keycloak, i see the flash of the jitsi-keycloak screen with some user info, and then the browser shows itself at url

https://meet.MY.DOMAIN[roomname]/?jwt=[token]

It seems some reason that the forward slash is being put after the room name instead of before, I'm not sure why.

Here's any variables/configs relating to urls where maybe I put something wrong.

Jitsi-env: 
```
TOKEN_AUTH_URL=https://meetsso.MY.DOMAIN/{room}
```
docker-compose for jitsi-keycloak:
```
            JITSI_URL: https://meet.MY.DOMAIN/
            JITSI_SUB: meet.MY.DOMAIN
```
nginx:
```
server {
...
    server_name meetsso.MY.DOMAIN;
...
    location / {
...
        proxy_pass http://jitsi-keycloak:port/;
    }
}
```
Keycloak:

```
valid redirection URIs: https://meetsso.MY.DOMAIN/*
web origins: https://meetsso.MY.DOMAIN
```

keycloak.json:

```
{
  "realm": "MY.DOMAIN",
  "auth-server-url": "https://sso.MY.DOMAIN/auth/",
  "ssl-required": "external",
  "resource": "jitsi",
  "public-client": true,
  "confidential-port": 0
}
```

**Comment by d3473r** [comment]
Hi, it looks like no room is set in the redirect, a valid url should look like this: https://meet.MY.DOMAIN/ROOM_NAME?jwt=
Have you set the `DEFAULT_ROOM` variable in your docker-compose? From which room are you making the request?
e.g. https://meet.MY.DOMAIN/ROOM_NAME

**Comment by brendan-mccoy** [comment]
Whoops, that's what I get for posting just before bed.

I meant to put

https://meet.[MY.DOMAIN][roomname]/?jwt=[token]

`            DEFAULT_ROOM: meeting`

**Comment by d3473r** [comment]
Okay, this is strange. I pushed an update making the url building more resilient against missing slashes.
Pull the latest image and tell me if the error still occurs for you

**Comment by brendan-mccoy** [comment]
Perfect! Thanks for your work!
