### ISSUE TITLE
npm-ci failures

### ISSUE THREAD

**Issue by vakaobr** [D3473R/jitsi-keycloak#3]
`npm-ci` has some stages failing because of missing packages.

Adding a `RUN apk add python3 make gcc g++ --no-cache` before `RUN npm ci` its enough to fix it :-)

**Comment by D3473R** [comment]
Fixed with https://github.com/D3473R/jitsi-keycloak/commit/ddb0b83768c33199ad1a0ac39904fa586cb70746.
Thanks :)
