### ISSUE TITLE
Add Avatar URL to JWT

### ISSUE THREAD

**Issue by Lumrenion** [d3473r/jitsi-keycloak#33]
I like how tihs container just works! Would it be possible to include the URL of an avatar image of keycloak users to the JWT?
JWT should be able to include such a URL and Jitsi seems to be able to handle that "avatar" parameter: https://community.jitsi.org/t/setting-avatar-using-jwt-token/92076

In Keycloak, the corresponding property can be added with a mapper, in the mappers tab of the client.

**Comment by d3473r** [comment]
Good idea 👍 
You can test it with `docker pull d3473r/jitsi-keycloak:develop` until i merge it into main
We don't even need a mapper as i am reading the user profile anyway, just add the `avatar` custom attribute to a user.
The avatar should also be displayed in the app bar in jitsi-keycloak:
<img width="291" alt="bar" src="https://user-images.githubusercontent.com/10356892/120669843-1e712b80-c490-11eb-9e95-80845bf75f15.png">

**Comment by Lumrenion** [comment]
Thank you a lot. I will probably test this out tomorrow and give you feedback then! 🙂

**Comment by Lumrenion** [comment]
It works like a charm 😊

**Comment by d3473r** [comment]
Perfekt 👍, i merged the changes into main, so the feature will also be available in the `latest` tag.
I am using this feature also for myself now :)
