### ISSUE TITLE
mobile phone usage

### ISSUE THREAD

**Issue by pascal1337** [d3473r/jitsi-keycloak#35]
Hey,

as I see the Jitsi mobile phone apps doesn't support `token_auth_url`.

Has anyone implemented a solution to authorize trough keycloak via mobile?

Best regards
Pascal

**Comment by devium** [comment]
You can visit the middleware website in your phone browser (something like auth.jitsi.example.com) and login from there. It will then direct you to the app just fine.

**Comment by d3473r** [comment]
As @devium said, this is a jitsi app limitation, nothing i can do about it. You can open jitsi-keycloak in the browser, and then switch to the app authorized.
