### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by pstackoverflow** [d3473r/jitsi-keycloak#39]
Hello,

I am struggling with jitsi-keycloak since few days now. I am getting CORS error like this in browser

Access to XMLHttpRequest at 'https://auth.MYDOMAIN.com/auth/realms/VC%20Realm/protocol/openid-connect/auth?client_id=vctestclient&state=e4bbde20-34e8-4d42-89ac-a1ac03724948&redirect_uri=http%3A%2F%2Fjk.MYDOMAIN.com%2Fapi%2Fconfig%3Fauth_callback%3D1&scope=openid&response_type=code' (redirected from 'https://jk.MYDOMAIN.com/api/config') from origin 'https://jk.MYDOMAIN.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Here is my setup:

    AWS EC2 running docker-jitsi-desktop with proper setting (ENABLE_AUTH=1, AUTH_TYPE=jwt and JWT_APP_ID=APPID )
    Another AWS EC2 running
    2.1) jitsi-keycloak started using docker-compose ( https://jk.MYDOMAIN.COM )
    2.2) keycloak ( https://auth.MYDOMAIN.COM ) and postgres inside separate docker containers using this docker compose file keycloak-containers/keycloak-postgres.yml at master · keycloak/keycloak-containers · GitHub AND
    2.3) an NGINX reverse proxy docker and letsencrypt sidecar docker using repo at GitHub - jwulf/letsencrypt-nginx-sidecar: Run letsencrypt and nginx in a docker-compose side car which starts keycloak and postgres docker containers . NGINX handles reverse proxy for jitsi-keycloak and keycloak. Letsencrypt sidecar automatically requests letsencrypt cert for associated domains.

I have done all the settings mentioned in GitHub - d3473r/jitsi-keycloak: Login to jitsi with keycloak https://hub.docker.com/r/d3473r/jitsi-keycloak but I keep getting this error in browser. My workflow currently is.

Visit jk.MYDOMAIN.com . This redirects to keycloak login page. Before putting credentials, I open the developer tools to see the console. When I click Sign In, I get logged in and immediately see this error (mentioned on the top of this writeup. Nothing happens when I enter the room name and press OPEN JITSI button. Nothing happens

Link to image from browser --> 
https://aws1.discourse-cdn.com/business4/uploads/jitsi/optimized/3X/6/7/6713d7ac14059fa744b41389e214e51e2bfee638_2_1380x144.png

Here is how keycloak is setup
https://aws1.discourse-cdn.com/business4/uploads/jitsi/optimized/3X/3/9/39a8f77a35da4bc5ab072c96cbc01f72f5ff60e8_2_1380x944.png

Here is the keycoak.json
https://aws1.discourse-cdn.com/business4/uploads/jitsi/optimized/3X/a/c/ac73b657bb8c03ed7e63f7e1f657fe172a3eafe5_2_1380x482.png

Please let me know what I am doing wrong. If you need more info please let me know and I will send quickly.

Thanks in advance

**Comment by d3473r** [comment]
Hi, do you have a trailing slash in your Web Origins Url?
![](https://user-images.githubusercontent.com/10356892/120615016-20b79380-c458-11eb-86cf-a70864319aae.png)

**Comment by pstackoverflow** [comment]
no I do not have a trailing slash. 

Btw, My issue was solved by using MASTER realm. 

But, when ever I create a new realm I get this same CORS error. So I created new realm (realm1), a new client inside this new realm and a new user inside this realm1. When I copied the keycloak.json from new client to jitsi-keycloak. When I try to use this new client to login, the login also happens, however I get this CORS error

I would really not like to use MASTER realm. How to solve this issue for NON-MASTER realm.

**Comment by d3473r** [comment]
That is very strange, i don't use the MASTER realm for my use case.
It should work in every realm.
Can you try it in a new realm, maybe you have configured something wrong in your realm settings

**Comment by pstackoverflow** [comment]
@d3473r this is still not solved for me. And the issue/error makes sense ..no? ​
Here are my domains

- Keycloak server : https://auth.MYDOMAIN.video
- jitsi-keycloak : https://jk.MYDOMAIN.video
- jitsi-meet : https://MYDOMAIN.video

From above, this is an issue about cross-origin.

From my understanding this is how the flow happens (assuming the flow is starting from jitsi-keycloak.

1. User visits https://jk.MYDOMAIN.video
2. Immediately browser redirects to https://auth.MYDOMAIN.video/auth/  (full url is https://auth.mydomain.video/auth/realms/VC%20Realm/protocol/openid-connect/auth?client_id=vctestclient&state=e4bbde20-34e8-4d42-89ac-a1ac03724948&redirect_uri=http%3A%2F%2Fjk.MYDOMAIN.com%2Fapi%2Fconfig%3Fauth_callback%3D1&scope=openid&response_type=code ) and presents a login screen to user
3. User enters credentials and is again redirected to https://jk.MYDOMAIN.video

This should create CORS error ...no?
Please let me know if my understanding is not correct or if my setup (of domains) is not correct

Thanks

**Comment by pstackoverflow** [comment]
I seem to have solved the above issue just by making sure there is no space between the name of my realm and client.

**Comment by pstackoverflow** [comment]
My issue with connectin.passwordRequired is solved. My JWT_APP_ID was different than 'jitsi' . Took a lot of debugging to solve this ..but atlast this is solved.
thanks
