### ISSUE TITLE
Jitsi error after login

### ISSUE THREAD

**Issue by hadirsa** [d3473r/jitsi-keycloak#40]
I did the steps on the readme and it worked. Now the `jitsi` needs a login with `keycloak` but there is an issue, the user cannot access the room and gets an error on the console that says `passwordRequired` :

<img width="708" alt="Screen Shot 2021-12-14 at 15 55 19" src="https://user-images.githubusercontent.com/3942854/145998303-67ef40c6-a3a7-4ffe-b814-4be8d77fdf60.png">

Is this a bug?

**Comment by d3473r** [comment]
Hi, did you set `AUTH_TYPE=jwt`?

**Comment by rtest12** [comment]
@hadirsa 
Did you manage to solve this problem? What was the reason? I got the same error.

**Comment by d3473r** [comment]
@rtest12 had the same error. The source was a reverse proxy misconfiguration: https://github.com/d3473r/jitsi-keycloak/issues/41#issuecomment-1013956229

Check your reverse proxy and open a new issue if the error still occures
