### ISSUE TITLE
Help with "Warning: connect.session() MemoryStore is not designed for a production environment"

### ISSUE THREAD

**Issue by rtest12** [d3473r/jitsi-keycloak#41]
when i run the command - 
`docker run -it --rm -p 3000:3000 -v $(pwd)/config:/config jitsi-keycloak`
I get error
`Error starting userland proxy: listen tcp4 0.0.0.0:3000: bind: address already in use.`
I don’t understand something, the keycloak itself is running on port 3000, so it’s busy, but how to get around this?

**Comment by d3473r** [comment]
You can adjust the port like so: docker run -it --rm -p 3001:3000 -v $(pwd)/config:/config jitsi-keycloak

**Comment by rtest12** [comment]
> You can adjust the port like so: docker run -it --rm -p 3001:3000 -v $(pwd)/config:/config jitsi-keycloak

Thank you. Now he throws out such a text, and nothing happens, what could be the matter?

**Comment by rtest12** [comment]
syslog:
```
systemd-udevd[19247]: veth6c4253c: Failed to get link config: No such device
systemd-udevd[19248]: veth6c4253c: Failed to get link config: No such device
sochifycloud4 systemd-networkd[673]: docker0: Lost carrier
```

**Comment by d3473r** [comment]
Looks like your docker network is broken, see https://vadosware.io/post/a-reliable-fix-to-docker-not-keeping-its-ipv4-address-on-arch/

**Comment by rtest12** [comment]
Apparently yes, but I can't find a reason, other containers work well

```
IDX LINK            TYPE     OPERATIONAL SETUP
  1 lo              loopback carrier     unmanaged
  2 eth0            ether    routable    configured
  3 br-5edce329d269 bridge   routable    unmanaged
  4 docker0         bridge   no-carrier  unmanaged
```

```
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:7bff:fe3c:c1f1  prefixlen 64  scopeid 0x20<link>
        ether 02:42:7b:3c:c1:f1  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 7  bytes 746 (746.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

```
kernel: [ 4598.437227] vethdcc55b7: renamed from eth0
networkd-dispatcher[710]: WARNING:Unknown index 17 seen, reloading interface list
kernel: [ 4598.454398] docker0: port 1(vethdeb7c25) entered disabled state
 systemd-networkd[679]: vethdeb7c25: Link DOWN
 kernel: [ 4598.459337] device vethdeb7c25 left promiscuous mode
 kernel: [ 4598.459340] docker0: port 1(vethdeb7c25) entered disabled state
systemd-networkd[679]: rtnl: received neighbor for link '18' we don't know about, ignoring.
systemd[3388]: run-docker-netns-da7e55638355.mount: Succeeded.
systemd[1]: run-docker-netns-da7e55638355.mount: Succeeded.
 systemd-udevd[4975]: vethdcc55b7: Failed to get link config: No such device
systemd[3388]: var-lib-docker-overlay2-46e7017993afc3d7b879fbbef31b944b90767e2b3f3a880a2c46f1bffccb1a77-merged.mount: Succeeded.
 systemd[1]: var-lib-docker-overlay2-46e7017993afc3d7b879fbbef31b944b90767e2b3f3a880a2c46f1bffccb1a77-merged.mount: Succeeded.
systemd-udevd[4971]: vethdcc55b7: Failed to get link config: No such device
systemd-networkd[679]: docker0: Lost carrier
```

**Comment by rtest12** [comment]
> You can adjust the port like so: docker run -it --rm -p 3001:3000 -v $(pwd)/config:/config jitsi-keycloak

should i change port to 3001 before running in files? app.js or .env? Or only when executing the command..
The error appeared at the stage "npm run dev"

```
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Function.listen (/home/user/jitsi-keycloak/server/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/user/jitsi-keycloak/server/src/app.js:78:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._compile (/home/user/jitsi-keycloak/server/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (/home/user/jitsi-keycloak/server/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
[nodemon] app crashed - waiting for file changes before starting...
10% building 2/2 modules 0 active[HPM] Proxy created: [Function: context]  ->  http://localhost:3000
[HPM] Subscribed to http-proxy events:  [ 'error', 'proxyReq', 'close' ]
98% after emitting CopyPlugin

 DONE  Compiled successfully in 36046ms                                                                         8:49:25 AM


  App running at:
  - Local:   http://localhost:8081/
  - Network: http://192.168.20.100:8081/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

[HPM] GET /api/keycloak.json -> http://localhost:3000
[HPM] GET /api/keycloak.json -> http://localhost:3000
```

**Comment by rtest12** [comment]
I freed 3000 port, but the problem is still not resolved by the network, it looks like it is a systemd problem, here is an example [https://github.com/systemd/systemd/issues/19428](url)
My version is just 245

**Comment by rtest12** [comment]
I checked on fresh instances of ubuntu sever 20.04 and ubuntu server 21.10 - same error.

**Comment by rtest12** [comment]
> 

I succeeded, but the container is started only manually, by id.

There was a new question ...
Everything is going well, after the redirect and authorization, a window appears with account data (last name, etc.) and the button to open jitsi, but after a second it disappears, and the "authorization error" window appears (Sorry! You are not allowed to be here). Console error "passwordRequired".

**Comment by rtest12** [comment]
@d3473r 
Help plzz
Prosody logs

> Error verifying token err:not-allowed, reason:token required

jwt decryption

> {
>   "alg": "HS256",
>   "typ": "JWT"
> }
> {
>   "context": {
>     "user": {
>       "name": "my name",
>       "email": "123@examle.com"
>     }
>   },
>   "aud": "jitsi",
>   "iss": "jitsi",
>   "sub": "meet.examle.com",
>   "room": "*",
>   "iat": 1641819066
> }

**Comment by d3473r** [comment]
How do you run jitsi-keycloak? Directly with npm or via the docker image d3473r/jitsi-keycloak?
Have you provided the config environment values?

**Comment by rtest12** [comment]
@d3473r 
> Have you provided the config environment values?

Certainly!

> How do you run jitsi-keycloak? Directly with npm or via the docker image d3473r/jitsi-keycloak?

As the instructions did not work for the reasons described above, I deleted -rm and ran like this
`docker run -it -p 3000: 3000 -v $ (pwd) / config: / config jitsi-keycloak`
After the error, it exited - docker ps - copied the id of the resulting container, and launched it through the "docker start coneinerid"

**Comment by d3473r** [comment]
Ah okay i see, with your run command there are no environment variables set. 
You need to set them with the `-e` flag eg. `-e JITSI_SECRET=SECRET`
The easiest way to setup the application is with the docker-compose.yml file in the example directory.
Place it in a folder add the keycloak config file in to the config directory, adjust the environment variables and start it with `docker-compose up -d`

**Comment by rtest12** [comment]
@d3473r 
I did through docker-compose, but nothing changed. Same error. The old container stopped, the new one was added and started. Docker restarted. It looks like the environment variables were working before. I don't even know what the matter is.

**Comment by d3473r** [comment]
Did you set `JITSI_SECRET` to the same value you configured in your jitsi .env file in `JWT_APP_SECRET`?

**Comment by rtest12** [comment]
@d3473r 
Sure, i add in yml
`JITSI_SECRET: jdoiwehfwhpefjdwouierfwjd989wdoqifuwidj9hi4uio3uif` 
And in .env jitsi
`JWT_APP_SECRET=jdoiwehfwhpefjdwouierfwjd989wdoqifuwidj9hi4uio3uif`
(edited)

**Comment by d3473r** [comment]
Okay, then it should work when you run it with `docker-compose up -d`
Can you check the network tab if a request is failing when you open jitsi?

**Comment by rtest12** [comment]
```
NETWORK ID     NAME                                       DRIVER    SCOPE
416018a3716b   bridge                                     bridge    local
5edce329d269   docker-jitsi-meet-stable-6173_meet.jitsi   bridge    local
b1604a692c58   host                                       host      local
cd95e8fd9a73   jitsi-keycloak_default                     bridge    local
d2ca61241d53   none                                       null      local
```

**Comment by d3473r** [comment]
The browser network tab please

**Comment by rtest12** [comment]
![111](https://user-images.githubusercontent.com/93929010/148803112-52eff014-9857-4da6-94af-88172d3fd792.png)

**Comment by d3473r** [comment]
Okay, so the app is redirecting you to jitsi with a jwt, but something is wrong with it.
Can you copy the jwt from the jitsi call? `meeting?jwt=...` If you click on the request you should see the jwt in the payload tab.
Insert it in a jwt debugger e.g. https://jwt.io/.
Then underneath there should be written `Invalid Signature`.
If you now copy your `JITSI_SECRET` and insert it on the lower right at `your-256-bit-secret` the message should now be `Signature Verified`

**Comment by rtest12** [comment]
```
{
  "alg": "HS256",
  "typ": "JWT"
}

{
  "context": {
    "user": {
      "name": "my name",
      "email": "123@example.com",
      "avatar": "https://example.com/avatar/31?etag=QgWDvfaK4fTi5QZ4Z"
    }
  },
  "aud": "jitsi",
  "iss": "jitsi",
  "sub": "meet.example.com",
  "room": "*",
  "iat": 1641832317
}
```
on the lower right

```
HMACSHA256(
  base64UrlEncode(header) + "." +
  base64UrlEncode(payload),
  
your-256-bit-secret

) secret base64 encoded

```


 Signature Verified

**Comment by d3473r** [comment]
Okay, perfect. Then everything from the jitsi-keycloak app works fine.
I think you have a configuration error on the jitsi side
How have you deployed it? I'm running mine with https://github.com/jitsi/docker-jitsi-meet

**Comment by rtest12** [comment]
@d3473r 
I completely deleted all containers and images, reloaded. A slightly different version was installed, probably an older one, I did
git clone https://github.com/jitsi/docker-jitsi-meet
Re-set all values in .env, but the errors are the same (((
The only thing that changed in my config is HTTPS_PORT=9443
And i have nginx proxy. 
my auth.meet.example.com config
```
server {
  server_name  auth.meet.example.com;
    listen 443 ssl;
    location / {
        proxy_pass           http://localhost:3000/;
```
And  meet.example.com config

server {
  server_name meet.example.com;


    listen 443 ssl; # managed by Certbot
    location / {
    proxy_pass_header Authorization;
    proxy_pass http://localhost:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_set_header Connection “”;
    proxy_buffering off;
    client_max_body_size 0;
    proxy_read_timeout 36000s;
    proxy_redirect off;
    }


    ssl_certificate /etc/letsencrypt/live/meet.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/meet.example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


ssl_stapling on;
ssl_stapling_verify on;

access_log  /var/log/nginx/meet_access.log;
error_log   /var/log/nginx/meet_error.log;


   location ~ ^/(colibri-ws|xmpp-websocket)$ {
        proxy_pass http://localhost:8000/$1;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

**Comment by rtest12** [comment]
@d3473r 
The point is apparently in the jitsi itself, because, if I manually create a token on jitok.emrah.com, paste it into the address bar jwt=, everything is the same. This is very strange, I have already set the simplest secret like 12345, I checked everything carefully up to the comma 10 times, but no ((

**Comment by d3473r** [comment]
Then maybe there is a big in the newest images of the docker-jitsi-meet project. I am running not the latest image i think

**Comment by rtest12** [comment]
@d3473r 
I'll try an older version in the evening, although, in theory, authorization should still work with a manually created token. Thank you for your help!

**Comment by d3473r** [comment]
Ahhh noo :D 
this could be indeed a nginx problem with websockets in nginx.
I've even build a modified nginx container because of that. (https://github.com/d3473r/nginx)
Try replacing `proxy_set_header Upgrade $http_upgrade;` with `proxy_set_header Connection $http_connection;`

**Comment by rtest12** [comment]
@d3473r 
It's funny that I tried to look for the problem not at all where it was :)
i'll explore this later, "proxy_set_header Connection $http_connection;" did not help

**Comment by rtest12** [comment]
Almost forgot, working config 
`
location ~ ^/colibri-ws/default-id/(.*) {
 proxy_pass http://127.0.0.1:8000/colibri-ws/default-id/$1$is_args$args;
 proxy_http_version 1.1;
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection "upgrade";
 tcp_nodelay on;
}
# colibri (JVB) websockets for jvb3
location ~ ^/colibri-ws/default-id/(.*) {
 proxy_pass http://127.0.0.1:8000/colibri-ws/default-id/$1$is_args$args;
 proxy_http_version 1.1;
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection "upgrade";
 tcp_nodelay on;
}

  location /xmpp-websocket {
      proxy_pass http://127.0.0.1:8000/xmpp-websocket;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
  }`

**Comment by d3473r** [comment]
Awesome 👍
