### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by skug67** [D3473R/jitsi-keycloak#5]
I seem to be able to get this project running so that it provides a keycloak protected http port which then forwards me to port 3000.  But I don't see how to get it integrated with my actual jitsi-meet app.  I'm assuming it's something I need to add into the jicofo config file.  Is there any documentation that would help explain that?

**Comment by D3473R** [comment]
Hi, I am using https://github.com/jitsi/docker-jitsi-meet#authentication-using-jwt-tokens with this,
You have to set `JWT_APP_ID=jitsi` and `JWT_APP_SECRET=your secret`.
Now you have to use the same secret in this app with `JITSI_SECRET=your secret` and it should sign the jwt correctly.

**Comment by Talanor** [comment]
Hello, I am running into the same problem. What I believe @skug67 meant (and my problem) is that we must do some configuration on the jitsi configuration to point to the server in order to delegate the authentication right ?
I couldn't find any information as to how to do that in your readme.
Thanks for the project anyway, looking forward to using it.

**Comment by D3473R** [comment]
Hi, this app is not called from the jitsi side.
You have to host this seperately from jitsi e.g on. `auth.meet.example.com` and login through this app.
You then will be redirected to jitsi with a valid JWT to automatically authenticate.
The jitsi app has to be configured with JWT auth and the same secret you are using here.

**Comment by rasos** [comment]
So if I got it right this app is just another frontend for jitsi-meet running on its own domain, but which requires login via a keycloak token. A default room name is set, but you can set your own room name. Maybe you could provide a screenshot in the README.

**Comment by D3473R** [comment]
After implementing the feature request from @teutat3s https://github.com/D3473R/jitsi-keycloak/issues/16 you can now redirect from jitsi to authenticate.
You have to set the `tokenAuthUrl: 'https://auth.meet.example.com/{room}',` in jitsi

**Comment by D3473R** [comment]
You can now set `TOKEN_AUTH_URL` in docker-jitsi-meet: https://github.com/jitsi/docker-jitsi-meet/pull/828
