### ISSUE TITLE
Please HELP. How works this jitsi-keycloack?

### ISSUE THREAD

**Issue by alex-fk** [d3473r/jitsi-keycloak#53]
Please HELP. How works this jitsi-keycloack? 
One host has Jitsi and Jitsi Keycloak installed in Docer. When there is a redirect from Jitsi to Jitsi-Keycloak on port 3000 error ERR_SSL_PROTOCOL_ERROR If you move Jitsi Keycloak to a separate host, http://kck.urd-jitsi-vks1.jitsimeethost.com:3000 authorization on keycloack passes but then an error Access to XMLHttpRequest at 'https://keycloak-int-test.jitsimeethost.com/auth/realms/office/account' from origin 'http://kck.urd-jitsi-vks1.jitsimeethost.com:3000/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by d3473r** [comment]
Hi, to fix the CORS error you have to add http://kck.urd-jitsi-vks1.jitsimeethost.com:3000/ to the Web Origins list in keycloak
