### ISSUE TITLE
Redirection straight to the conference (but not to the "start the meeting page")

### ISSUE THREAD

**Issue by drusov** [d3473r/jitsi-keycloak#75]
Hello!
First of all thank you for the brilliant "connector". It saved lots of effort and time for me.
We've managed to make it up and running pretty fast.
It is more like feature request or may be just an advice.

Now it works like:
Create meeting -> "i am the host" -> autoredirect to the app -> authenticate -> redirect to the button start of the meeting -> meeting it self.
In this approach user gets his Name autofilled - but it still can be changed by him. And in our idea we don't want authenticated users to have the possibility to change their names.
 
Is it possible to make a login flow go like this:
Create meeting -> "i am the host" -> autoredirect to the app -> authenticate -> autoredirect to the meeting itself.

Thanks in advance,
Denis.

**Comment by d3473r** [comment]
Hi,

sorry for the late reply.
I don't think this is anything this app can influence (via a query param for example)
You can try different [settings](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#features-configuration-configjs) for your jitsi instance.
I would try disabling `ENABLE_WELCOME_PAGE` or `ENABLE_PREJOIN_PAGE`

Regards
