### ISSUE TITLE
did you configure CORS correctly?

### ISSUE THREAD

**Issue by celevra** [d3473r/jitsi-keycloak#78]
Hi,

i get an alert windows with the Question "Did you configure CORS correctrly"
but if i take a look into the console i can't find cors errors, only one 401 error against the keycloak:

```
keycloak.mjs:776     POST https://login.xxx.xxx/realms/xxx/protocol/openid-connect/token 401 (Unauthorized)
```

any ideas?

**Comment by d3473r** [comment]
Hmm, maybe you have a typo in your realm or client-id.
Cann you attach a screenshot of the client settings in keycloak?

**Comment by celevra** [comment]
<img width="894" alt="image" src="https://github.com/d3473r/jitsi-keycloak/assets/232437/09e70b9f-18d6-49cb-8691-df549722b31c">

**Comment by d3473r** [comment]
Thanks :)
You configured the client as a confidential client.
But it should be configured as a public one, as this is a browser app which cannot hold secrets: https://oauth.net/2/client-types/

For comparison, my keycloak config looks like this:
``` json
{
  "realm": "realm",
  "auth-server-url": "https://iam.example.com/auth",
  "ssl-required": "external",
  "resource": "client",
  "public-client": true,
  "confidential-port": 0
}
```

<img width="747" alt="Screenshot 2023-09-25 at 10 37 02" src="https://github.com/d3473r/jitsi-keycloak/assets/10356892/7ca7713d-6d17-4920-8fad-9af34d372607">

**Comment by celevra** [comment]
thank you, from there i came a step further but had curs issues that where strange to me (we have a dozen of clients in our keycloak that are not having cors issues).
To keep it short: you showed me the simple idea: an app that authenticates via keycloak and then signs a jwt and redirects back.
We had everything we needed in node so that we hacked a little script. 
thanks for you help and time
