### ISSUE TITLE
Authenticate from Rocket.Chat

### ISSUE THREAD

**Issue by imedia3** [d3473r/jitsi-keycloak#81]
Hi, is there any chance to set up this app to be used with Rocket.Chat [jitsi app](https://www.rocket.chat/apps/jitsi-meet) ? 
For now Jitsi returns "You are not allowed to be there". 
Jitsi's Prosody returns "Token ...long-token... not allowed to join rc...@muc.meet.jitsi/2044c63a"

**Comment by imedia3** [comment]
bump

**Comment by imedia3** [comment]
@d3473r

**Comment by d3473r** [comment]
Hi, sorry for the late reply.

As i read the rocket.chat docs correctly there is no need for this app when using jitsi in rocket.chat.
The authentication is already done in rocket.chat via JWT signing: https://docs.rocket.chat/use-rocket.chat/rocket.chat-conference-call/conference-call-admin-guide/jitsi-app

Can you tell me more about your use case if this doesn't fit your needs?
