### ISSUE TITLE
Error Cors

### ISSUE THREAD

**Issue by namtel-hp** [D3473R/jitsi-keycloak#9]
Pls help my case

![t](https://user-images.githubusercontent.com/62697590/87121674-7bc72180-c2ad-11ea-9a29-ed940692dab1.jpg)

**Comment by D3473R** [comment]
Hi, you have to add the apps domain to your keycloak web origins array, otherwise the browser will block the request because of the missing CORS header. https://huongdanjava.com/configure-web-origin-in-keycloak.html

**Comment by namtel-hp** [comment]
Keycloak

![22](https://user-images.githubusercontent.com/62697590/87128395-be8ef680-c2b9-11ea-9aea-3afb7ae339b6.jpg)

Still same CORS error 
and then Add :
        pathRewrite: {
          '^/api': ''
in vue.config.js  > Error cors gone but error like:

![12](https://user-images.githubusercontent.com/62697590/87128955-be432b00-c2ba-11ea-8a45-157a3333c708.jpg)
![21](https://user-images.githubusercontent.com/62697590/87128957-bf745800-c2ba-11ea-90f1-cf8c1c80a7ab.jpg)
![333](https://user-images.githubusercontent.com/62697590/87128958-c00cee80-c2ba-11ea-9465-f46b3460e959.jpg)

**Comment by namtel-hp** [comment]
Hi,
Keyloack
![22](https://user-images.githubusercontent.com/62697590/87129156-18dc8700-c2bb-11ea-868b-1f4f6484aa41.jpg)

Result same error

then I add 
        pathRewrite: {
          '^/api': ''

Then CORS gone but error: undefined.

![12](https://user-images.githubusercontent.com/62697590/87129301-4b867f80-c2bb-11ea-958e-1eac3310fffd.jpg)
![21](https://user-images.githubusercontent.com/62697590/87129302-4cb7ac80-c2bb-11ea-84c4-bfcb2c2f17d2.jpg)
![333](https://user-images.githubusercontent.com/62697590/87129303-4d504300-c2bb-11ea-8fe9-7c1a43e6b570.jpg)

**Comment by namtel-hp** [comment]
Dear,
Please help to show me your config vue.config.js
Thanks
