### ISSUE TITLE
disconnects of jitsi when using connector

### ISSUE THREAD

**Issue by drusov** [d3473r/jitsi-keycloak#91]
Hello!
We found a very weird stuff when applied jitsi-keycloak adapter in the environment.
We got installation of keycloak and jitsi both in k8s.
When we added connector to the environment we started to experience disconnects during the conferences when connecting or disconnecting to the VPN.
And this happens only when we got auth enabled. When we don't have the connector enabled, VPN doesn't have any impact on the connections during the conferences.
Do you have any ideas what could be wrong? and where to look at?

**Comment by d3473r** [comment]
This is strange, but i think this has nothing to do with this app.
This app only attaches the jwt as query param to the jitsi url
I would open an issue at the docker-jitsi-meet repo: https://github.com/jitsi/docker-jitsi-meet
