### ISSUE TITLE
cors popup when running on keycloak 25

### ISSUE THREAD

**Issue by tob123** [d3473r/jitsi-keycloak#96]
Hi,

after upgrading to keycloak 25 i get a popup similar to what is described in https://github.com/d3473r/jitsi-keycloak/issues/78 
rolling back to 24 including dbrestore gives me a working setup.

Anybody else encountering issues after upgrading to keycloak 25 when using this nice software ?
version i used specifically: 25.0.1

regards,

Tobias.

**Comment by zukka77** [comment]
I had the same issue, I opened a pull request with updated libraries: https://github.com/d3473r/jitsi-keycloak/pull/94
no reply so far.
This works for me :sweat_smile: https://github.com/zukka77/jitsi-keycloak/tree/feat/kc25

**Comment by tob123** [comment]
wow. great work. thanks a lot for posting this. will test myself and share results. @d3473r any remarks from you on the PR ?

**Comment by d3473r** [comment]
Hi, the PR is merged and is working with my keycloak 22 instance, can you test again with 25?

**Comment by tob123** [comment]
looks mighty good. thanks for these quick updates!!

**Comment by ykorzikowski** [comment]
confirm its working :)
